import assert from 'node:assert/strict';
import * as THREE from 'three';
import {ActorModels,applyActorPose,focusPose,isMobileActor} from '../static/actor-models.js';
globalThis.document={getElementById:()=>null};
const view={scene:new THREE.Scene(),node:{dataset:{}},render(){},camera:new THREE.PerspectiveCamera(50,1,.1,2000),controls:{target:new THREE.Vector3(),update(){}},renderer:{domElement:{getBoundingClientRect:()=>({left:0,top:0,width:500,height:500})}}};
const models=new ActorModels(view);let loads=0;
models.template=async()=>{loads++;const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.BoxGeometry(4,2,2)));return g};
const actor=(id,type='vehicle.test.car',x=0)=>({id,type,pose:{x,y:0,z:1,yaw:0},extent:{x:2,y:1,z:1}});
models.update([actor(25),actor(31,'vehicle.test.car',20),actor(32,'walker.pedestrian.0043',-20)],null);
await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(view.node.dataset.actorModels,'3');assert.equal(view.node.dataset.actorCones,'0');
const root=models.entries.get(25).root,geometry=root.children[0].children[0].geometry;
models.update([actor(25,'vehicle.test.car',5),actor(31,'vehicle.test.car',20),actor(32,'walker.pedestrian.0043',-20)],25);
assert.equal(models.entries.get(25).root,root);assert.equal(root.position.x,5);assert.equal(loads,3,'pose updates must reuse loaded models');assert.equal(view.node.dataset.actorCones,'1');assert.equal(models.pin.position.x,5);
models.update([actor(25),actor(31,'vehicle.test.car',20)],31);assert.equal(view.node.dataset.actorCones,'1');assert.equal(models.pin.position.x,20);assert(!models.entries.has(32));
models.update([actor(25)],31);assert.equal(view.node.dataset.actorCones,'0');assert.equal(root.children[0].children[0].geometry,geometry,'removing an actor must not dispose shared model geometry');
view.camera.position.set(0,10,20);view.camera.lookAt(0,1,0);view.camera.updateMatrixWorld(true);
assert.equal(models.pick({clientX:250,clientY:250}).id,25,'double-click picking must resolve visible actor bounds');
models.focus(25);assert.equal(view.node.dataset.focusedActor,'25');assert(view.controls.target.distanceTo(new THREE.Vector3(0,2,0))<1e-6);
const object=new THREE.Object3D();applyActorPose(object,{x:2,y:3,z:4,yaw:90});assert.deepEqual(object.position.toArray(),[2,4,3]);assert(new THREE.Vector3(1,0,0).applyQuaternion(object.quaternion).distanceTo(new THREE.Vector3(0,0,1))<1e-6);
assert(!isMobileActor({type:'sensor.camera.rgb'}));assert(!isMobileActor({type:'traffic.traffic_light'}));
let resolveTemplate;models.template=()=>new Promise(resolve=>{resolveTemplate=resolve});models.update([actor(99)],99);models.update([],null);resolveTemplate(new THREE.Group());await new Promise(resolve=>setTimeout(resolve,0));assert.equal(models.group.children.length,0,'late model fetch must not resurrect a removed actor');
console.log('PASS: cached actor transforms, one selected cone, actor removal, async stale load, oriented picking, camera focus and coordinate conversion');
