import fs from 'node:fs';import zlib from 'node:zlib';import * as THREE from 'three';
const manifest=JSON.parse(fs.readFileSync('static/scenes/Town10HD_Opt/manifest.json')),b=zlib.gunzipSync(fs.readFileSync('static/scenes/Town10HD_Opt/'+manifest.layers[0].file)),length=b.readUInt32LE(),meta=JSON.parse(b.subarray(4,4+length)),base=(4+length+3)&~3;
const array=(r,T=Float32Array)=>new T(b.buffer,b.byteOffset+base+r[0],r[1]);
const source=process.argv.includes('--source')?JSON.parse(fs.readFileSync('data/scene-source/scene.json')):null,raw=source?fs.readFileSync('data/scene-source/geometry.bin'):null;const sourceArray=(r,T=Float32Array)=>new T(raw.buffer,raw.byteOffset+r[0],r[1]);const meshes=[];
for(const batch of (source?Object.values(source.groups):meta.groups).filter(g=>/SM_Town10HD_(Road|LaneMarking)_/.test(g.mesh))){const transforms=source?Float32Array.from(batch.transforms.flat()):array(batch.transforms);for(const sec of (source||meta).meshes[batch.mesh].sections){const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.BufferAttribute((source?sourceArray:array)(sec.position),3));geom.setIndex(new THREE.BufferAttribute((source?sourceArray:array)(sec.index,Uint32Array),1));for(let i=0;i<(source?batch.transforms.length:batch.count);i++){const t=transforms.subarray(i*10,i*10+10),mesh=new THREE.Mesh(geom,new THREE.MeshBasicMaterial({side:THREE.DoubleSide}));mesh.position.fromArray(t);mesh.quaternion.fromArray(t,3);mesh.scale.fromArray(t,7);mesh.updateMatrixWorld(true);meshes.push(mesh)}}}
if(process.argv.includes('--junction-test')){const ray=new THREE.Raycaster();let missing=0;for(let x=-50;x<=-40;x+=.5)for(let y=17;y<=28;y+=.5){ray.set(new THREE.Vector3(x,3,y),new THREE.Vector3(0,-1,0));if(!ray.intersectObjects(meshes).length)missing++}console.log({junctionSamples:483,missing});if(missing)process.exit(1);process.exit(0)}
const map=JSON.parse(fs.readFileSync('data/map-cache.json')),ray=new THREE.Raycaster(),missing=[],heights=[];let samples=0;
for(const lane of map.lanes)for(const p of lane.points){samples++;ray.set(new THREE.Vector3(p[0],p[2]+5,p[1]),new THREE.Vector3(0,-1,0));const hits=ray.intersectObjects(meshes);if(!hits.length)missing.push({lane:lane.id,junction:lane.junction,x:p[0],y:p[1],z:p[2]});else heights.push(hits[0].point.y-p[2]);}
const result={meshes:meshes.length,samples,missing:missing.length,missingJunction:missing.filter(p=>p.junction).length,heightRange:[Math.min(...heights),Math.max(...heights)],examples:missing.slice(0,15)};fs.writeFileSync(source?'data/road-coverage-source.json':'data/road-coverage.json',JSON.stringify(result,null,2));console.log(result);
