"""Public MCP schemas; no CARLA imports and no simulator ownership."""
def obj(properties=None, required=(), **extra):
    return {'type':'object','properties':properties or {},'required':list(required),'additionalProperties':False,**extra}
def enum(*values): return {'type':'string','enum':list(values)}
def num(low=None, high=None):
    return {'type':'number',**({'minimum':low} if low is not None else {}),**({'maximum':high} if high is not None else {})}
def integer(low=0, high=None): return {**num(low,high),'type':'integer'}
STR={'type':'string','minLength':1}; BOOL={'type':'boolean'}; ANY={'type':'object'}
ID=integer(1); SID={'type':'string','pattern':r'^[A-Za-z0-9_-]+$','maxLength':128}
POINT=obj({**{k:num() for k in ('x','y','z','yaw','pitch','roll')},'parking_space':STR},('x','y'))
MOUNT=obj({k:num(-360,360) for k in ('x','y','z','yaw','pitch','roll')})
TYPES=('sensor.camera.rgb','sensor.camera.depth','sensor.camera.semantic_segmentation','sensor.camera.instance_segmentation','sensor.camera.normals','sensor.camera.optical_flow','sensor.lidar.ray_cast','sensor.lidar.ray_cast_semantic','sensor.other.radar','sensor.other.imu','sensor.other.gnss')
SENSOR=obj({'name':{'type':'string','pattern':'^[a-z][a-z0-9_]{0,39}$'},'type':enum(*TYPES),'mount':MOUNT,'attributes':{'type':'object','additionalProperties':{'type':'string'}}},('name','type','mount','attributes'))
SENSORS={'type':'array','items':SENSOR,'maxItems':16}
PHASE=obj({'name':STR,'duration':num(.5,600),'states':{'type':'object','additionalProperties':obj({k:enum('Stop','Protected','Permissive','Off') for k in ('left','straight','right')})}},('duration','states'))
PLAN=obj({'flows':{'type':'array','maxItems':32,'items':obj({'id':STR,'model':STR,'spawn':integer(),'destination':integer(),'start':num(0,86400),'interval':num(1,3600),'count':integer(1,1000),'remove_arrived':BOOL},('id','model','spawn','destination','count'))},'events':{'type':'array','maxItems':256,'items':obj({'id':STR,'time':num(0,86400),'action':enum('spawn_vehicle','spawn_pedestrian','destination','weather','signal_phase','signal_hold','signal_resume'),'model':STR,'spawn':integer(),'destination':integer(),'actor':{'type':['string','integer']},'preset':enum('clear','cloudy','rain','sunset','night'),'group_id':ID,'index':integer()},('id','action'))}})
TOOLS={}
def add(name,description,schema=None,*,action=None,path=None,method='GET',mode='json',read=True,example=None):
    TOOLS['carla_'+name]={'description':description,'schema':schema or obj(),'action':action,'path':path,'method':'POST' if action else method,'mode':mode,'read':read,'example':example or {}}
def cmd(name,action,desc,schema=None,example=None):add(name,desc,schema,action=action,read=False,example=example)
EDIT=' Requires paused live simulation with recording stopped.'
LIVE=' Works running or paused; stop recording and native replay first. Advances a synchronization frame.'
for name,path,desc in [('status','status','Read live runtime, actors, routes, vehicle controls, weather, signals, sensors, occupancy, GPU timings and operation progress.'),('catalog','catalog','Read installed vehicle/pedestrian models and sensor blueprint attributes.'),('map','map','Read OpenDRIVE-derived roads, lane directions/turns, sidewalks, walking points, spawn points and surveyed parking including exclusions.'),('configuration','configuration','Export the complete reusable scenario configuration. This request is serialized with simulator operations.'),('sessions','sessions','List recording manifests, frame counts, status and ROS bag availability.'),('log','log','Read the last 6 KB of simulator output.')]:add(name,desc,path='/api/'+path)
add('opendrive','Read the original OpenDRIVE XML. Surveyed parking and pedestrian overlays are in carla_map, not written into this XML.',path='/api/map.xodr',mode='text')
add('capabilities','Read the WebUI feature mapping, tool schemas and examples.',mode='capabilities')
add('latency','Measure one MCP-bridge-to-WebUI status round trip in milliseconds; this is not browser latency or simulation speed.',mode='latency')
cmd('start','start','Start the owned CARLA simulator group asynchronously. Poll carla_status until connected; do not repeat start.',obj({'gpus':enum('auto','3','0,1,2,3')}),{'gpus':'auto'})
cmd('connect','connect','Connect to the existing local CARLA on port 2000. No other client may own its clock.')
cmd('shutdown','shutdown','Stop the owned CARLA group and workers, or disconnect an external simulator. This destroys the current owned runtime; export configuration first if needed.')
cmd('run','run','Advance the shared synchronous simulation continuously, or resume native replay.')
cmd('pause','pause','Pause the shared simulation clock; sensor previews may still read the last completed sample.')
cmd('step','step','Advance one synchronous frame. Do this while paused for controlled stepping; setup operations may also advance frames.')
cmd('spawn','spawn','Spawn an ego, background vehicle or pedestrian. Ego omission of sensors adds six defaults. For parked placement use background role and parking_space; spawn may be omitted in that case.'+EDIT,obj({'role':enum('ego','background','pedestrian'),'model':STR,'planner':enum('tm','external'),'spawn':POINT,'destination':{'anyOf':[POINT,{'type':'null'}]},'parking_space':STR,'sensors':SENSORS},('role','model'),anyOf=[{'required':['spawn']},{'required':['parking_space']}]),{'role':'ego','model':'vehicle.lincoln.mkz_interior','planner':'tm','spawn':{'x':0,'y':0}})
cmd('delete_actor','delete','Remove a managed actor and its attached sensors/walker controller.'+EDIT,obj({'id':ID},('id',)),{'id':52})
cmd('destination','destination','Replace the active goal immediately, including during recording. Road points snap to lanes; parking_space selects a validated bay. TM drives reverse parking; external ego receives an exact goal without control takeover. Pedestrians use walkable points. Rejects native replay.',obj({'id':ID,'point':POINT,'arrival_tolerance':num(.25,3)},('id','point')),{'id':52,'point':{'x':8,'y':63,'parking_space':'P024'}})
add('pedestrian_path','Check pedestrian route reachability without changing the destination.',obj({'id':ID,'point':POINT},('id','point')),action='pedestrian-path',example={'id':60,'point':{'x':0,'y':0}})
cmd('control','control','Apply external ego throttle, steer, brake and reverse through vehicle physics. Existing external control watchdog brakes after one wall-clock second. Use a dedicated HTTP/ROS control loop for continuous driving; MCP is not a real-time controller.',obj({'id':ID,'throttle':num(0,1),'steer':num(-1,1),'brake':num(0,1),'reverse':BOOL},('id',)),{'id':52,'throttle':0,'steer':0,'brake':1,'reverse':False})
cmd('convert_scene_vehicles','convert-scene-vehicles','Convert remaining native scenery vehicles to managed background actors; reports substitutions and failures.'+EDIT)
cmd('move_parked_to_road','parked-to-road','Explicitly reposition a parked scene vehicle onto a road and enable Traffic Manager. This is placement, not a driven departure; use destination for physical departure.'+EDIT,obj({'id':ID,'point':POINT},('id','point')),{'id':34,'point':{'x':0,'y':0}})
cmd('reload_parking','reload-parking','Reload validated on-disk parking annotations without restarting the world. Stop recording and replay first.')
cmd('configure_sensors','sensors','Replace the entire ego loadout; empty list removes all sensors. Mount is vehicle-local metres/degrees; attributes are strings. May allocate GPU workers and warm cameras for 30 frames.'+EDIT,obj({'id':ID,'sensors':SENSORS},('id','sensors')),{'id':52,'sensors':[]})
weather={k:num(0,100) for k in ('cloudiness','precipitation','precipitation_deposits','wind_intensity','fog_density','wetness','dust_storm','fog_falloff','scattering_intensity','mie_scattering_scale','rayleigh_scattering_scale')}
weather.update(sun_azimuth_angle=num(0,360),sun_altitude_angle=num(-90,90),fog_distance=num(0,10000))
cmd('weather','weather','Apply any subset of the supported weather fields to the synchronized scene.'+LIVE,obj(weather,minProperties=1),{'sun_altitude_angle':-25,'cloudiness':20,'precipitation':0})
cmd('traffic_light','traffic-light','Set native approach colour, hold its intersection, resume cycle, or edit durations. Movement programs must be disabled and clearance finished first. Holding sets other approaches red.'+LIVE,obj({'id':ID,'operation':enum('state','timing','resume'),'state':enum('Red','Yellow','Green','Off'),'hold':BOOL,'scope':enum('signal','intersection'),**{k:num(.1,600) for k in ('green_time','yellow_time','red_time')}},('id','operation'),allOf=[{'if':{'properties':{'operation':{'const':'state'}}},'then':{'required':['state']}},{'if':{'properties':{'operation':{'const':'timing'}}},'then':{'required':['green_time','yellow_time','red_time']}}]),{'id':10,'operation':'state','state':'Red','hold':True})
cmd('movement_program','movement-program','Enable/update protected and permissive left/straight/right phases, hold, resume, select phase or disable. Conflicting protected paths and unsupported turns are rejected. Edits use yellow/all-red clearance; phase index is zero-based.'+LIVE,obj({'group_id':ID,'operation':enum('enable','update','disable','hold','resume','phase'),'phases':{'type':'array','items':PHASE,'minItems':1,'maxItems':16},'yellow_time':num(.5,30),'all_red_time':num(.5,30),'index':integer(0,15),'hold':BOOL},('group_id','operation'),allOf=[{'if':{'properties':{'operation':{'const':'phase'}}},'then':{'required':['index']}}]),{'group_id':10,'operation':'enable','yellow_time':3,'all_red_time':2})
cmd('network_timing','network-timing','Select independent, coordinated common-cycle/offset, or demand-adaptive timing. Coordinated/adaptive requires fully applied movement plans at every intersection.'+LIVE,obj({'mode':enum('independent','coordinated','adaptive'),'cycle_time':num(1,3600),'offsets':{'type':'object','additionalProperties':num(0,3600)},'min_green':num(.5,120),'max_green':num(.5,600),'gap':num(.5,15),'distance':num(5,100)},('mode',)),{'mode':'adaptive','min_green':5,'max_green':30,'gap':2,'distance':40})
cmd('configure_schedule','authoring-configure','Replace the full flows/events schedule. Stop the schedule first. Uses zero-based map spawn/walking point indices and simulation-relative seconds.'+EDIT,obj({'config':PLAN},('config',)),{'config':{'flows':[],'events':[{'id':'nightfall','time':30,'action':'weather','preset':'night'}]}})
cmd('start_schedule','authoring-start','Arm the saved schedule relative to current simulation time. Run or step afterward to execute departures/events.'+EDIT)
cmd('stop_schedule','authoring-stop','Stop future schedule execution. Already spawned actors remain; pending automatic arrival cleanup also stops.')
cmd('gpu_profile','gpu-profile','Apply automatic or up-to-N GPU worker policy; may recreate sensor streams. Preserves sensor quality.'+EDIT,obj({'profile':enum('auto','1','2','3','4')},('profile',)),{'profile':'auto'})
cmd('gpu_benchmark','gpu-benchmark','Measure GPU worker counts with three 50-frame windows per count. Advances the evolving scene, recreates sensor streams, and can take several minutes. Preserves quality.'+EDIT)
cmd('record_start','record-start','Arm native recorder plus exact state/raw sensor capture and optional ROS 2 bag. Requires live mode, ROS and at least 5 GiB free. Run or step to capture.',obj({'rosbag':BOOL}),{'rosbag':True})
cmd('record_stop','record-stop','Finalize the recording, ROS bag and integrity manifest.')
cmd('replay_native','replay-native','Replace current actors with a completed recording in native CARLA replay. Requires owned simulator; regenerated sensors are not bit-identical originals.'+EDIT,obj({'id':SID,'start':num(0),'autoplay':BOOL},('id',)),{'id':'REPLACE_WITH_SESSION_ID','start':0,'autoplay':True})
cmd('replay_stop','replay-stop','Stop native replay and asynchronously restart owner and CARLA into a clean live scene. Poll status through temporary API unavailability; existing replay actors are discarded.')
cmd('restore_configuration','restore-configuration','Restore an exported configuration into an empty managed scene. Not a physics checkpoint. Restores actors/sensors/weather/signals/parking/schedule; leaves simulation paused.'+EDIT,obj({'configuration':ANY},('configuration',)))
add('recover','Restart a failed owned simulator using its saved recovery configuration. Only available in error state; actor IDs and time can change. Poll status until ready.',path='/api/recover',method='POST',read=False)
add('session_frame','Read exact recorded states and sensor file references by zero-based recording index.',obj({'session_id':SID,'index':integer()},('session_id','index')),path='/api/sessions/{session_id}/frame/{index}',example={'session_id':'REPLACE_WITH_SESSION_ID','index':0})
add('session_files','List recorded session files and byte sizes.',obj({'session_id':SID},('session_id',)),path='/api/sessions/{session_id}/files')
add('verify_session','Verify a stopped recording: hashes, frame/sample continuity and timestamps. Saves verification.json; does not re-simulate.',obj({'session_id':SID},('session_id',)),path='/api/sessions/{session_id}/verify',method='POST',read=False)
add('compare_sessions','Compare stopped recordings by configured actor order and recording-relative frames, including trajectories and signals. Separate from byte integrity.',obj({'reference':SID,'candidate':SID},('reference','candidate')),path='/api/compare',method='POST')
add('sensor_preview','Fetch ONE latest requested sensor preview only. Image default returns an MCP image plus frame/timestamp metadata; points returns bounded binary as an embedded resource; IMU/GNSS return JSON. after suppresses identical frames. Does not run or subscribe to sensors.',obj({'sensor_id':ID,'width':integer(160,960),'after':integer(-1),'format':enum('image','points'),'point_limit':integer(512,12000)},('sensor_id',)),path='/api/preview/{sensor_id}',mode='preview',example={'sensor_id':53,'width':640,'after':-1})
add('recorded_preview','Read the saved frame’s first RGB camera as a 640-pixel JPEG. Use session files for other original camera samples.',obj({'session_id':SID,'index':integer()},('session_id','index')),path='/api/sessions/{session_id}/preview/{index}',mode='preview')
add('session_file','Read one session file, capped at 2 MiB. Binary is an embedded resource; large files return an error with a download URL. Paths must be relative and traversal-free.',obj({'session_id':SID,'filename':STR},('session_id','filename')),path='/api/sessions/{session_id}/files/{filename}',mode='file')
add('download_links','Get direct WebUI links without downloading archives/raw sensor datasets into model context. kind=session requires session_id; optional filename chooses one file.',obj({'kind':enum('session','opendrive','parking_review','webui'),'session_id':SID,'filename':STR},('kind',)),mode='links',example={'kind':'parking_review'})
add('scene_manifest','Read the current map’s exported browser geometry/texture manifest and base URL without loading the meshes.',mode='scene')

add('inspect','Read selected top-level status/map/catalog/configuration fields. Page a single array or object field to keep large maps out of model context. No scene mutation.',obj({'source':enum('status','map','catalog','configuration'),'fields':{'type':'array','items':STR,'minItems':1},'offset':integer(),'limit':integer(1,500)},('source','fields')),mode='inspect',example={'source':'map','fields':['parking_spaces'],'offset':0,'limit':10})
